import streamlit as st
import json
import requests
import os
import matplotlib.pyplot as plt
import streamlit.components.v1 as components


from collections import defaultdict

from generate import GenerateEmail
import data_handling as dh
import functionality as fnc




# --- CONFIG ---
st.set_page_config(page_title="AI Email Editor", page_icon="📧", layout="wide")

# datasets register
DEMO_DATASETS = {
    "lengthen" : "/Users/itang/Music/servicenow_bootcamp/ai_bootcamp_starter/datasets/lengthen.jsonl",
    "shorten" : "/Users/itang/Music/servicenow_bootcamp/ai_bootcamp_starter/datasets/shorten.jsonl",
    "tone" : "/Users/itang/Music/servicenow_bootcamp/ai_bootcamp_starter/datasets/tone.jsonl",
    'test' : '/Users/itang/Music/servicenow_bootcamp/ai_bootcamp_starter/datasets/test.jsonl',
}

# --- INITIALIZE ALL SESSION STATE VARIABLES ---
fnc.initialize_session_states(
    dataset_name = 'lengthen',
    dataset = None,
    email_id = 1,
    model_name = 'gpt-4.1',
    edit_method = 'Lengthen',
)



# Send flag after successfully editing the LLM advanced settings
if st.session_state.tmp_setting_save:
    st.session_state.tmp_setting_save = False
    st.toast("Settings saved!")

# --- UI HEADER ---
st.title("📧 AI Email Editing Suite")


# suite tab and analytics tabs
suite_tab, analytics_tab = st.tabs(['Email Suite', 'Analytics']) #, "🔍 Diff View"


# ===== EMAIL SUITE =====
with suite_tab:
    # --- small descripotion ---
    st.write("Select an email record by ID and use AI to refine it!")
    # partition workspace
    controls, workspace = st.columns([1, 3], gap="medium")

    # --- CONTROL SETTINGS BAR ---
    with controls:
        with st.container(border=True):
            st.subheader("Configuration")

            # ===== DATA SELECTION =====
            # dropdown to choose the dataset you want to load
            dataset_name = st.selectbox(
                label="Select the dataset.", 
                options=list(DEMO_DATASETS.keys()),
                key="dataset_name",
                accept_new_options=False, 
                on_change=fnc.sync_email_dataset,
            )

            # store into emails and load dataset (no need to do this if dataset is being selected)
            # emails = fnc.load_data(dataset_name)
            # st.session_state.dataset = emails
            emails = st.session_state.dataset

            # --- ID NAVIGATION BAR ---
            # currently a bug where switching dataset while having a selected number does not switch to the nearest number, goes to 1 and displays 1 even when the value is different
            email_ids = emails.keys() # this will error if you change to a dataset with less values, so make sure it fits
            selected_id = st.selectbox(
                label="📂 Select Email ID",
                options=email_ids,
                index=0,
                key='email_id',
                on_change=fnc.sync_email_id,
            )
            
            st.divider()
            # ===== MODEL PARAMS =====
            # --- CHOOSE BASE MODEL ---
            selected_model = st.selectbox(
                label="Choose LLM Base Model",
                options=['gpt-4.1', 'gpt-4o-mini'],
                index=0,
                key='model_name',
                on_change=fnc.sync_llm,
            )

            # --- CHOOSE EMAIL TRANSFORM METHOD ---
            # Maybe add an option to create your own with custom prompts.
            edit_method = st.selectbox(
                label="Choose edit method",
                options=['Lengthen', 'Shorten', 'Tone'],
                index=0,
                key='edit_method',
            )

            # --- ADVANCED EDIT MODE ---   
            if st.button("Advanced Settings"):
                fnc.advanced_llm_settings_form()

            st.divider()
            # ===== EVALUATION AND PROMPTS =====
            # --- choose eval metric ---
            evaluation_metrics = st.multiselect(
                label="Choose evaluation metrics",
                options=st.session_state.llm.evaluation_metrics,
                key="evaluation_metrics",
                help="All metrics generated by default.",
            )
            # --- COLLECT ADDITIONAL CONTEXT ---
            with st.expander("Additional Context"):
                context = st.text_area(
                    label="Add optional context here:",
                    height=250,
                    key='extra_context',
                    placeholder="Make the tone sad because my cat ate my homework.",
                )
            
            edit_subject = st.toggle("Edit subject line?", key="edit_subject_toggle")

            # --- get email generator object ---
            llm = st.session_state.llm

            # retrieve email at selected id
            original_email = fnc.Email(emails.get(selected_id, ""))
            generated_email = fnc.Email() # phony generated email to be generate when generate button is clicked


            # --- GENERATE BUTTON ---
            with st.spinner(f"Generating {edit_method.lower() if edit_method != 'tone' else 'ton'}ed email..."):
                generate_button = st.button("Generate")
                if generate_button:
                    print("Generate prompts")
                    generated_email = fnc.generate_email(original_email)
                    st.success("New email generated!")

    with workspace:
        # Email header data
        with st.container(border=True):
            st.info(f"✉️ Email ID: **{selected_id}**")
            m1, m2 = st.columns([0.1, 0.9])
            with m1:
                # Avatar placeholder
                st.markdown("# 👤")
            with m2:
                l1, l2 = st.columns(2)
                with l2.container(horizontal_alignment='right'):
                    st.markdown("**To:** [insert destination address]")  
                l1.markdown("**From:** [alice@example.com]")
                st.markdown("**Date:** [Sun 1/4/2026 10:42 AM]")
        
        with st.container(border=True):
            tab_edit, tab_preview = st.tabs(["📝 Side-by-Side Editor", "👁️ Preview"])

            with tab_edit:
                # display original and edited boxes
                original, generated = st.columns(2)
                with original:
                    # -- Create headers ---
                    st.markdown("## Original")
                    st.markdown(f"**Subject:** {original_email.subject}")
                    # st.session_state
                    st.text_area(
                        label = "Original Content",
                        height = 250,
                        key = 'original_textbox_suite',
                        placeholder="Select editing method to see output!",
                    )

                with generated:
                    st.markdown("## Edited")
                    st.markdown(f"**Subject:** {st.session_state.generated_subject}") 
                    st.text_area(
                        label = "Edited Content",
                        height = 250,
                        key = 'generated_textbox_suite',
                        placeholder="Select editing method to see output!",
                    )
            
            with tab_preview:
                st.caption("This is how the recipient will see your email:")
        
                fnc.render_gmail_preview(
                    email_subject=st.session_state.generated_subject,
                    email_body=st.session_state.generated_textbox_suite, # The variable holding your generated email
                    height=600
    )
                if st.button("📋 Copy", type='primary', help="Copy to clipboard", key="copy_generated_email"):
                    st.write(st.session_state) # In reality, use pyperclip or js hack, use something here idk lol
                    st.toast("✅ Copied to clipboard!")


        
# ===== ANALYTICS =====
with analytics_tab:
    fnc.test()


    





    


    

            








       




    # Purpose of this page: Show off the capabilities of the app without requiring sign up.
    
    # Show the saved analytics, allow user to create a new email, but the email will not be going anywhere.
    # It will essentually just be a text generator.



    # The other page will allow a user to sign in to the website and connect directly to their gmail accounts to create a message.
    # They can send the edited message from there, and also have some other possible generative capabilities.
    # - maybe sign off?
    # - maybe image generation?
    # - idk lol



